import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'production', 'test').default('development'),
  PORT: Joi.number().default(3000),
  API_PREFIX: Joi.string().default('api'),
  CORS_ORIGINS: Joi.string().when('NODE_ENV', {
    is: 'production',
    then: Joi.required(),
    otherwise: Joi.allow('').optional(),
  }),
  TRUST_PROXY_HOPS: Joi.number().integer().min(0).max(10).default(0),
  ENABLE_SWAGGER: Joi.string().valid('true', 'false').optional(),
  DB_HOST: Joi.string().required(),
  DB_PORT: Joi.number().default(5432),
  DB_USERNAME: Joi.string().required(),
  DB_PASSWORD: Joi.string().required(),
  DB_PASSWORD_FILE: Joi.string().optional(),
  DB_DATABASE: Joi.string().required(),
  DB_SYNCHRONIZE: Joi.string().valid('true', 'false').default('false'),
  REDIS_HOST: Joi.string().default('localhost'),
  REDIS_PORT: Joi.number().default(6379),
  REDIS_PASSWORD: Joi.string().allow('').optional(),
  REDIS_PASSWORD_FILE: Joi.string().optional(),
  REDIS_DB: Joi.number().default(0),
  AUTH_MODE: Joi.string().valid('jwt', 'session').default('jwt'),
  SESSION_COOKIE_NAME: Joi.string().default('meago_sid'),
  SESSION_IDLE_TTL_MINUTES: Joi.number().integer().min(1).max(1440).default(30),
  SESSION_ABSOLUTE_TTL_DAYS: Joi.number().integer().min(1).max(365).default(14),
  SESSION_TOUCH_INTERVAL_SECONDS: Joi.number().integer().min(0).max(3600).default(60),
  SESSION_CACHE_TTL_SECONDS: Joi.number().integer().min(1).max(3600).default(300),
  JWT_ACCESS_SECRET: Joi.string().min(32).required(),
  JWT_ACCESS_SECRET_FILE: Joi.string().optional(),
  JWT_ACCESS_TTL: Joi.string().default('15m'),
  JWT_ISSUER: Joi.string().default('meago-server'),
  JWT_AUDIENCE: Joi.string().default('meago-client'),
  JWT_REFRESH_TTL_DAYS: Joi.number().default(14),
  JWT_REFRESH_RACE_GRACE_SECONDS: Joi.number().integer().min(0).max(30).default(5),
  JWT_REFRESH_COOKIE_NAME: Joi.string().default('meago_rt'),
  PERMISSION_CACHE_TTL_MS: Joi.number().default(300000),
  AUTH_LOCK_TIMEOUT_MS: Joi.number().integer().min(100).max(30000).default(5000),
  APP_RELEASE: Joi.string().optional(),
  SENTRY_DSN: Joi.string().uri().allow('').optional(),
  SENTRY_DSN_FILE: Joi.string().optional(),
  SENTRY_TRACES_SAMPLE_RATE: Joi.number().min(0).max(1).default(0),
});
