import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'production', 'test').default('development'),
  PORT: Joi.number().default(3000),
  DB_HOST: Joi.string().required(),
  DB_PORT: Joi.number().default(5432),
  DB_USERNAME: Joi.string().required(),
  DB_PASSWORD: Joi.string().required(),
  DB_PASSWORD_FILE: Joi.string().optional(),
  DB_DATABASE: Joi.string().required(),
  DB_SYNCHRONIZE: Joi.string().valid('true', 'false').default('false'),
  REDIS_HOST: Joi.string().default('localhost'),
  REDIS_PORT: Joi.number().default(6379),
  REDIS_PASSWORD: Joi.string().allow('').optional(),
  REDIS_PASSWORD_FILE: Joi.string().optional(),
  REDIS_DB: Joi.number().default(0),
  JWT_ACCESS_SECRET: Joi.string().min(32).required(),
  JWT_ACCESS_SECRET_FILE: Joi.string().optional(),
  JWT_ACCESS_TTL: Joi.string().default('15m'),
  JWT_ISSUER: Joi.string().default('meago-server'),
  JWT_AUDIENCE: Joi.string().default('meago-client'),
  REFRESH_TOKEN_TTL_DAYS: Joi.number().default(14),
  REFRESH_RACE_GRACE_SECONDS: Joi.number().integer().min(0).max(30).default(5),
  REFRESH_COOKIE_NAME: Joi.string().default('meago_rt'),
  PERMISSION_CACHE_TTL_MS: Joi.number().default(300000),
  APP_RELEASE: Joi.string().optional(),
  SENTRY_DSN: Joi.string().uri().allow('').optional(),
  SENTRY_DSN_FILE: Joi.string().optional(),
  SENTRY_TRACES_SAMPLE_RATE: Joi.number().min(0).max(1).default(0),
});
